### ISSUE TITLE
Red Package Manager/ Plug in management stategy

### ISSUE THREAD

**Issue by RyanLassigBanks** [aludvik/red#1]
I love the idea of Red, but I feel like no editor is complete until it has a package manager 😉

**Comment by hannahedavis** [comment]
I would also appreciate some customizable key bindings.

**Comment by aludvik** [comment]
There are already a lot of text editors / IDEs that support these features well. Red's primary goal is to be a zero-configuration text editor that works one way, the "right way", out-of-the-box, to avoid the hassle of needing to setup and configure your text editor every time you need to use it on a new system. The above features, though useful and popular in general, are contrary to this goal. ;)
